### ISSUE TITLE
Not really an issue, just a suggestion

### ISSUE THREAD

**Issue by malcommac** [sachinkesiraju/SKPanoramaView#2]
I've tried to download this package (both from cocoapods and directly from github).
I think that over 130mb of gif/images for less than 100kb of class sources does not make much sense. You should link these images externally or make a smaller version of them.

**Comment by sachinkesiraju** [comment]
You're right. I shouldn't have added the gifs to the repo. I just removed them from the project and linked them externally. Thanks for the feedback.
