### ISSUE TITLE
Get Received memory warning.

### ISSUE THREAD

**Issue by shahchirag2110** [sachinkesiraju/SKPanoramaView#5]
When i put this view as it is for some time i get "Received memory warning." error and crash after some time because of memory warning.

**Comment by sachinkesiraju** [comment]
Hmm I wasn't able to reproduce the crash. Do you think you could send me a crash log?

**Comment by shahchirag2110** [comment]
Okay let me give you step by step information
1) I just want to make same intro screen which is in linkedin application getting started screen.
2) So i take 3 skpanaromaview and when i scroll right or left present view alpha will be decrease and other view alpha is increase.
3) So if i put this screen as it is for 5 min i get "Received memory warning." message and then crash.

**Comment by sachinkesiraju** [comment]
You shouldn't need to use 3 panoramaviews simultaneously. Check out the sample code on the README on how to implement the Linkedin-style behavior correctly, there should only need to be one instance of SKPanoramaView running.
